/*
 * Maltiverse API
 *
 * Maltiverse API
 *
 * API version: 1.0.0
 * Contact: root@maltiverse.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package maltiverse

type BlItem struct {
	Description string `json:"description"`
	Source      string `json:"source"`
	// First date when the blacklist blame was noticed. If no specified takes the current date value. This date can't point to the future and must be less or equal than last_seen
	FirstSeen string `json:"first_seen,omitempty"`
	// Last date when the blacklist blame was noticed. If no specified takes the current date value. This date can't point to the future and must be greater or equal than first_seen
	LastSeen string `json:"last_seen,omitempty"`
}
