/*
 * Maltiverse API
 *
 * Maltiverse API
 *
 * API version: 1.0.0
 * Contact: root@maltiverse.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package maltiverse

type LocationItem struct {
	Lat float32 `json:"lat"`
	Lon float32 `json:"lon"`
}
