/*
 * Maltiverse API
 *
 * Maltiverse API
 *
 * API version: 1.0.0
 * Contact: root@maltiverse.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package maltiverse

type URLItem struct {
	URL            string   `json:"url"`
	Type_          string   `json:"type"`
	Classification string   `json:"classification"`
	Tag            []string `json:"tag,omitempty"`
	Blacklist      []BlItem `json:"blacklist,omitempty"`
	// The the date when the indicator is created. If no specified takes the current date value
	CreationTime string `json:"creation_time,omitempty"`
	// The the date when the indicator got its last modification. If no specified takes the current date value
	ModificationTime string `json:"modification_time,omitempty"`
}
